language: dart

dart:
  - stable
  - dev

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - ls ~
  - export PATH=~/flutter/bin:$PATH
  - flutter doctor

script:
  - ls
  - (cd packages/dart && dart pub get)
  - (cd packages/dart && dart test test/)
  - (cd packages/flutter && flutter pub get)
  - (cd packages/flutter && flutter test --no-pub test/)

cache:
  directories:
    - "$HOME/.pub-cache"