name: parse_server_sdk_flutter
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.28
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk:
    path: ../dart/

  # Networking
  dio: ^3.0.10
  connectivity: ^0.4.9+2 # only used in the flutter part

  #Database
  shared_preferences: ^0.5.10 # only used in the flutter part

  # Utils
  path_provider: ^1.6.14 # only used in the flutter part
  package_info: ^0.4.3 # only used in the flutter part

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
